Update workflows

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,52 +1,60 @@
-name: running test,build image, push registry, deploy
+name: running test, build image, push registry, deploy
+
 on:
   push:
     branches: [main]
 
 jobs:
-  runningtest:
-    name: running test
+  running_test:
+    name: Running Test
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-go@v2
+      - name: Checkout Repository
+        uses: actions/checkout@v2
+      - name: Set Up Go
+        uses: actions/setup-go@v2
         with:
           go-version: "1.20"
-      - name: run test
+      - name: Run Tests
         run: go test -v ./... -cover
 
-  buildimage:
-    name: build image
+  build_image:
+    name: Build Image
     runs-on: ubuntu-latest
-    needs: runningtest
+    needs: running_test
     steps:
-      - name: checkout
+      - name: Checkout Repository
         uses: actions/checkout@v2
-      - name: build image
+      - name: Build Docker Image
         run: docker build -t faqihazh/alta:latest .
-      - name: login registry
+      - name: Log in to Docker Registry
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-      - name: push image
+      - name: Push Docker Image
         run: docker push faqihazh/alta:latest
 
-  deployec2:
-    name: deploy ec2
+  deploy_ec2:
+    name: Deploy EC2
     runs-on: ubuntu-latest
-    needs: buildimage
+    needs: build_image
     steps:
-      - uses: actions/checkout@v2
-      - name: deploy ec2
+      - name: Checkout Repository
+        uses: actions/checkout@v2
+      - name: Deploy to EC2
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.SSH_HOST }}
           username: ${{ secrets.SSH_USER }}
           key: ${{ secrets.SSH_KEY }}
           script: |
-            cd /home
-            # docker compose down
-            docker pull faqihazh/alta:latest
-            docker run -d -p 1323:1323 faqihazh/alta:latest
-            # docker compose up -d
+            # Pastikan Docker diinstal di instance EC2
+            which docker || echo "Docker is not installed or not found in PATH."
+
+            # Jalankan perintah
+            cd /home || echo "Directory not found."
+            docker-compose down || echo "Failed to stop previous containers."
+            docker pull faqihazh/alta:latest || echo "Failed to pull latest image."
+            docker run -d -p 1323:1323 faqihazh/alta:latest || echo "Failed to run container."
+            docker-compose up -d || echo "Failed to start containers."
